### PR TITLE
import .env file

### LINKED ISSUE #4: Define a way to set env vars on host server before deploying
Most apps use env vars set in the local machine or in .env files.
We need to define a way to let the user to set the env vars he wants to set in the host server, before deploy takes place.

### PR DESCRIPTION
**Pull request by saitodisse**
Your local .env file will be copied to remote server before deploy.

This closes #4

### CODE REVIEW

**Comment by fearenales** [comment]
@saitodisse I think the best option is to have a env var `ENV_FILE`, which default value is `.env` and specifies which file will be copied.

In this way, we can have separated .env files for different environments (test, production, ...)

**Comment by saitodisse** [comment]
Good point, I will change this.

**Comment by saitodisse** [comment]
@fearenales, is there an way to get this dynamic?

```
src=/azk/deploy/src/{{ env_file }}
```

Is this mount fixed?

``` js
      '/azk/deploy/src' : path('.'),
```

**Comment by saitodisse** [comment]
Ok, I got it: `LOCAL_PROJECT_PATH`

``` yml
---
- hosts: all
  sudo: true
  tasks:
    - name: Copy .env to server
      copy:
        src={{ local_project_path }}/{{ env_file }}
        dest={{ remote_project_path }}/.env
        owner={{ user }}
        mode=0600
```

**Comment by fearenales** [comment]
;)

**Comment by gullitmiranda** [comment]
LGTM =D

**Pull request merged**
